events {
    worker_connections 1024;
}

stream {
    upstream user_db {
        server postgres-user:5432;
    }

    upstream product_db_primary {
        server postgres-product-primary:5432;
    }

    upstream product_db_replica {
        server postgres-product-replica:5432;
    }

    upstream transaction_db {
        server postgres-transaction:5432;
    }

    upstream redis_server {
        server redis:6379;
    }

    upstream mongo_server {
        server mongo:27017;
    }

    server {
        listen 15432;
        proxy_pass user_db;
    }

    server {
        listen 15433;
        proxy_pass product_db_primary;
    }

    server {
        listen 15434;
        proxy_pass product_db_replica;
    }

    server {
        listen 15435;
        proxy_pass transaction_db;
    }

    server {
        listen 16379;
        proxy_pass redis_server;
    }

    server {
        listen 17017;
        proxy_pass mongo_server;
    }
}